"""24절기 상세 데이터 — 의미·풍습·키워드."""

SOLAR_TERM_DETAIL = {
    0: {
        "name": "입춘(立春)",
        "name_en": "Ipchun (Beginning of Spring)",
        "approx_date": "2월 4일경",
        "longitude": 315,
        "month_branch": "寅(인)",
        "meaning": "봄의 시작. 사주의 한 해가 새로 시작되는 가장 중요한 절기.",
        "saju_meaning": "이 시점을 기준으로 사주의 연주가 바뀝니다. 입춘 직전 출생자는 전년도 연주를 사용합니다.",
        "tradition": "옛부터 ‘입춘대길(立春大吉)’ 글귀를 대문에 붙여 한 해의 길운을 빌었습니다.",
        "keyword": "시작·성장·기획",
    },
    1: {
        "name": "우수(雨水)",
        "name_en": "Usu (Rain Water)",
        "approx_date": "2월 19일경",
        "longitude": 330,
        "month_branch": "寅(인)",
        "meaning": "얼었던 눈이 비로 변하기 시작하는 시기. 봄기운이 본격화.",
        "saju_meaning": "인월(寅月) 중반. 봄 기운이 안정적으로 자리 잡습니다.",
        "tradition": "농가에서 봄 농사 준비를 시작하는 시기.",
        "keyword": "변화·전환",
    },
    2: {
        "name": "경칩(驚蟄)",
        "name_en": "Gyeongchip (Awakening of Insects)",
        "approx_date": "3월 6일경",
        "longitude": 345,
        "month_branch": "卯(묘)",
        "meaning": "동면하던 동물들이 깨어나는 시기. 천둥소리에 벌레가 놀라 나옵니다.",
        "saju_meaning": "묘월(卯月)의 시작. 사주에서 본격적인 봄 운기로 진입합니다.",
        "tradition": "한국에서는 보리싹의 성장을 점쳐 한 해 농사의 풍흉을 가늠했습니다.",
        "keyword": "각성·움직임",
    },
    3: {
        "name": "춘분(春分)",
        "name_en": "Chunbun (Spring Equinox)",
        "approx_date": "3월 21일경",
        "longitude": 0,
        "month_branch": "卯(묘)",
        "meaning": "낮과 밤의 길이가 같아지는 봄의 한가운데.",
        "saju_meaning": "음양이 균형을 이루는 시기. 묘월의 정중앙.",
        "tradition": "춘분에 친친 머리를 묶으면 한 해 두통이 없다는 옛말이 있었습니다.",
        "keyword": "균형·중심",
    },
    4: {
        "name": "청명(淸明)",
        "name_en": "Cheongmyeong (Clear and Bright)",
        "approx_date": "4월 5일경",
        "longitude": 15,
        "month_branch": "辰(진)",
        "meaning": "하늘이 맑고 밝은 시기. 봄 농사의 결정적 시기.",
        "saju_meaning": "진월(辰月)의 시작. 사주에서 봄의 토(土) 기운이 자리 잡습니다.",
        "tradition": "한식과 가까운 시기로, 조상 묘를 살피는 풍습이 있었습니다.",
        "keyword": "청량·실행",
    },
    5: {
        "name": "곡우(穀雨)",
        "name_en": "Gogu (Grain Rain)",
        "approx_date": "4월 20일경",
        "longitude": 30,
        "month_branch": "辰(진)",
        "meaning": "곡식을 자라게 하는 비가 내리는 시기.",
        "saju_meaning": "진월 후반. 토 기운이 절정에 이릅니다.",
        "tradition": "봄 가뭄이 끝나고 본격적인 농사 시즌이 시작됩니다.",
        "keyword": "성장·축적",
    },
    6: {
        "name": "입하(立夏)",
        "name_en": "Ipha (Beginning of Summer)",
        "approx_date": "5월 6일경",
        "longitude": 45,
        "month_branch": "巳(사)",
        "meaning": "여름의 시작. 만물이 무성하게 자라기 시작합니다.",
        "saju_meaning": "사월(巳月)의 시작. 사주의 화 기운으로 진입합니다.",
        "tradition": "보리 수확 직전, 보리고개의 끝자락.",
        "keyword": "확장·열정",
    },
    7: {
        "name": "소만(小滿)",
        "name_en": "Soman (Grain Filling)",
        "approx_date": "5월 21일경",
        "longitude": 60,
        "month_branch": "巳(사)",
        "meaning": "곡식이 어느 정도 자라 가득 차기 시작.",
        "saju_meaning": "사월 후반. 양 기운이 빠르게 자랍니다.",
        "tradition": "보리 수확이 본격화됩니다.",
        "keyword": "충만·발전",
    },
    8: {
        "name": "망종(芒種)",
        "name_en": "Mangjong (Awn Grains)",
        "approx_date": "6월 6일경",
        "longitude": 75,
        "month_branch": "午(오)",
        "meaning": "까끄라기가 있는 곡식(보리·밀)을 심는 시기.",
        "saju_meaning": "오월(午月)의 시작. 화 기운의 정점으로 향합니다.",
        "tradition": "보리 수확과 모내기가 동시에 이루어지는 가장 바쁜 시기.",
        "keyword": "집중·실천",
    },
    9: {
        "name": "하지(夏至)",
        "name_en": "Haji (Summer Solstice)",
        "approx_date": "6월 21일경",
        "longitude": 90,
        "month_branch": "午(오)",
        "meaning": "1년 중 낮이 가장 긴 날.",
        "saju_meaning": "양 기운의 정점. 이후 음 기운이 자라기 시작합니다.",
        "tradition": "하지 감자를 캐는 시기.",
        "keyword": "절정·전환점",
    },
    10: {
        "name": "소서(小暑)",
        "name_en": "Soseo (Slight Heat)",
        "approx_date": "7월 7일경",
        "longitude": 105,
        "month_branch": "未(미)",
        "meaning": "본격적인 더위가 시작되는 시기.",
        "saju_meaning": "미월(未月)의 시작. 사주에서 여름 토 기운으로 진입.",
        "tradition": "보리 수확이 끝나고 본격적인 여름 농사 시즌.",
        "keyword": "성숙·축적",
    },
    11: {
        "name": "대서(大暑)",
        "name_en": "Daeseo (Great Heat)",
        "approx_date": "7월 23일경",
        "longitude": 120,
        "month_branch": "未(미)",
        "meaning": "1년 중 가장 더운 시기.",
        "saju_meaning": "미월 후반. 화 기운이 최후의 절정에 이릅니다.",
        "tradition": "삼복더위. 보양식을 먹는 시기.",
        "keyword": "극한·인내",
    },
    12: {
        "name": "입추(立秋)",
        "name_en": "Ipchu (Beginning of Autumn)",
        "approx_date": "8월 8일경",
        "longitude": 135,
        "month_branch": "申(신)",
        "meaning": "가을의 시작. 더위 속에서도 가을 기운이 싹틉니다.",
        "saju_meaning": "신월(申月)의 시작. 금(金) 기운으로 진입.",
        "tradition": "곡식 결실이 시작되는 시기.",
        "keyword": "수확·결단",
    },
    13: {
        "name": "처서(處暑)",
        "name_en": "Cheoseo (End of Heat)",
        "approx_date": "8월 23일경",
        "longitude": 150,
        "month_branch": "申(신)",
        "meaning": "더위가 그치고 서늘함이 들어오는 시기.",
        "saju_meaning": "신월 후반. 금 기운이 안정적으로 자리 잡습니다.",
        "tradition": "벼가 익기 시작.",
        "keyword": "전환·정리",
    },
    14: {
        "name": "백로(白露)",
        "name_en": "Baekro (White Dew)",
        "approx_date": "9월 8일경",
        "longitude": 165,
        "month_branch": "酉(유)",
        "meaning": "아침에 흰 이슬이 내리기 시작.",
        "saju_meaning": "유월(酉月)의 시작. 금 기운의 정점으로 향합니다.",
        "tradition": "벼 이삭이 패는 시기.",
        "keyword": "결실·정밀",
    },
    15: {
        "name": "추분(秋分)",
        "name_en": "Chubun (Autumn Equinox)",
        "approx_date": "9월 23일경",
        "longitude": 180,
        "month_branch": "酉(유)",
        "meaning": "낮과 밤의 길이가 같아지는 가을의 한가운데.",
        "saju_meaning": "음양이 다시 균형을 이루는 시기. 유월의 정중앙.",
        "tradition": "본격적인 가을 수확 시작.",
        "keyword": "균형·결실",
    },
    16: {
        "name": "한로(寒露)",
        "name_en": "Hanro (Cold Dew)",
        "approx_date": "10월 8일경",
        "longitude": 195,
        "month_branch": "戌(술)",
        "meaning": "이슬이 차갑게 변하는 시기.",
        "saju_meaning": "술월(戌月)의 시작. 가을 토 기운으로 진입.",
        "tradition": "단풍이 본격화됩니다.",
        "keyword": "정리·수렴",
    },
    17: {
        "name": "상강(霜降)",
        "name_en": "Sanggang (First Frost)",
        "approx_date": "10월 23일경",
        "longitude": 210,
        "month_branch": "戌(술)",
        "meaning": "서리가 내리기 시작.",
        "saju_meaning": "술월 후반. 금 기운이 마무리되고 토로 응축됩니다.",
        "tradition": "가을 수확 마무리.",
        "keyword": "응축·마무리",
    },
    18: {
        "name": "입동(立冬)",
        "name_en": "Ipdong (Beginning of Winter)",
        "approx_date": "11월 7일경",
        "longitude": 225,
        "month_branch": "亥(해)",
        "meaning": "겨울의 시작.",
        "saju_meaning": "해월(亥月)의 시작. 사주의 수(水) 기운으로 진입.",
        "tradition": "김장 준비가 시작됩니다.",
        "keyword": "저장·준비",
    },
    19: {
        "name": "소설(小雪)",
        "name_en": "Soseol (Slight Snow)",
        "approx_date": "11월 22일경",
        "longitude": 240,
        "month_branch": "亥(해)",
        "meaning": "첫눈이 내리는 시기.",
        "saju_meaning": "해월 후반. 수 기운이 자리 잡습니다.",
        "tradition": "김장이 본격화됩니다.",
        "keyword": "내면화·집중",
    },
    20: {
        "name": "대설(大雪)",
        "name_en": "Daeseol (Great Snow)",
        "approx_date": "12월 7일경",
        "longitude": 255,
        "month_branch": "子(자)",
        "meaning": "큰 눈이 내리는 시기.",
        "saju_meaning": "자월(子月)의 시작. 수 기운의 정점으로 향합니다.",
        "tradition": "겨울이 깊어지는 시기.",
        "keyword": "깊이·사색",
    },
    21: {
        "name": "동지(冬至)",
        "name_en": "Dongji (Winter Solstice)",
        "approx_date": "12월 22일경",
        "longitude": 270,
        "month_branch": "子(자)",
        "meaning": "1년 중 밤이 가장 긴 날.",
        "saju_meaning": "음 기운의 정점. 이후 양 기운이 자라기 시작합니다.",
        "tradition": "팥죽을 먹어 액운을 막는 풍습.",
        "keyword": "전환점·재시작",
    },
    22: {
        "name": "소한(小寒)",
        "name_en": "Sohan (Slight Cold)",
        "approx_date": "1월 6일경",
        "longitude": 285,
        "month_branch": "丑(축)",
        "meaning": "작은 추위. 본격적인 한파가 시작되는 시기.",
        "saju_meaning": "축월(丑月)의 시작. 겨울 토 기운으로 진입.",
        "tradition": "‘소한 추위는 꿔다가도 한다’는 속담.",
        "keyword": "응축·인내",
    },
    23: {
        "name": "대한(大寒)",
        "name_en": "Daehan (Great Cold)",
        "approx_date": "1월 20일경",
        "longitude": 300,
        "month_branch": "丑(축)",
        "meaning": "1년 중 가장 추운 시기.",
        "saju_meaning": "축월 후반. 수 기운이 마무리되고 토로 응축됩니다.",
        "tradition": "곧 입춘이 다가오는 마지막 절기.",
        "keyword": "극한·결말",
    },
}


def get_term(idx):
    return SOLAR_TERM_DETAIL.get(idx)
